config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :books
end

app/models/book.rb
class Book < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(books_params)
    if @book.save

      redirect_to books_path
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update_attributes!(books_params)

    redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:id]).delete

    redirect_to books_path
  end

  private
  def books_params
    params.require(:book).permit(:name, :author)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<%= form_for @book do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.submit 'Update book' %>
  </p>
<% end %>

app/views/books/index.html.erb
<%= form_for @book do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
  <p>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.submit 'Add book' %>
  </p>
<% end %>

<%= @books.each do |book| %>
<ul>
  <li>
    <%= link_to "#{book.name}", book_path(book) %>, <%= book.author %>
  </li>
</ul>
<% end %>

app/views/books/show.html.erb
<ul>
  <li>
    <%= @book.name %>, <%= @book.author %>
  </li>
</ul>

<%= link_to 'Edit', edit_book_path %>
<%= link_to 'Delete', book_path(@book), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudBooks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to 'Add a book', books_path %>